import { describe, expect, it } from 'vitest';
import { classesEmployeesHtml } from './classes';
import primitivesHtml from '../../primitives.html?raw';

/**
 * THE LIST OF CASES THE PRIMITIVES GALLERY SHOWS — never
 * `galerie-primitives.ts`, which carries NONE.
 *
 * 🔴 THIS FILE DOES NOT IMPORT `./galerie-primitives`. Like `galerie.ts` (see
 * `galerie.test.ts`), this module touches `document.getElementById` from its
 * first useful line, with no injected dependency, and `client/` has NEITHER jsdom
 * NOR happy-dom: importing it would make the module crash on load.
 *
 * ⚠️ BUT THE REASON A TEST CANNOT SAY ANYTHING MORE ABOUT THIS
 * PARTICULAR FILE IS NOT ONLY THE ABSENCE OF A DOM. Unlike
 * `galerie.ts`, whose header declares that the list of tokens is
 * PARSED from it, `galerie-primitives.ts` states in black and white "it reads NO
 * TOKEN": its seventeen lines only do one wiring of the theme
 * selector (`installThemeSelectorInDOM`, ALREADY fully tested by
 * `selecteur-theme.test.ts`, with no dependency specific to this module).
 * There is therefore, in `galerie-primitives.ts` itself, neither a testable DOM nor
 * a list of cases to freeze — the two reasons why `galerie.test.ts`
 * has something to say have no counterpart here.
 *
 * ⚠️ WHAT "THE PRIMITIVES GALLERY" REALLY SHOWS — four families,
 * button/field/surface/message, each with its variants and states — is
 * STATIC markup, written by hand in `client/primitives.html`, never
 * generated by TypeScript (see that file's header: "the split
 * gave birth to `client/primitives.html` beside it"). It is therefore IT that carries
 * "the list of cases" of this gallery — and it is therefore it that this file
 * freezes, not a module that knows nothing about it.
 *
 * ⚠️ WHAT IS ALREADY COVERED ELSEWHERE, AND IS NOT REPEATED HERE: that
 * `primitives.css` does DECLARE these variants and states — guards G1 to
 * G7 of `primitives.test.ts`, which read `primitives.css`. This file
 * checks something else: that the DEMONSTRATION PAGE SHOWS them. A
 * primitive declared but absent from the markup would be seen by no
 * human eye, and by no existing guard either — that is the hole this
 * file closes.
 *
 * 🔴 THE RED THIS FILE CAN PRODUCE: removing a demonstration block
 * from `primitives.html` (for example the `message--danger` line) brings down
 * the test of its family — the primitive has disappeared from what the gallery
 * shows, and the test asks for it.
 *
 * ⚠️ NO VISUAL JUDGEMENT: that the hover reads, that a tone stands apart from
 * its neighbour by ink alone — the human judgements the header of
 * `primitives.html` names itself (eight from spec ⑥ §8, plus four from S2,
 * fifteen at the end of S3). Batch 4, not this one.
 *
 * ⚠️ "NO DUPLICATE" IS NOT A SEPARATE TEST HERE: the classes
 * are read into a `Set` (no duplicate possible by construction), and
 * `message--flottant` appears twice IN THE MARKUP — two lengths of
 * text for the SAME variant, a deliberate demonstration choice, not a
 * repetition a test should denounce.
 */

const CLASSES = classesEmployeesHtml(primitivesHtml);

/** The names of `attendues` absent from `CLASSES` — same pattern as `etatsManquants` of `primitives.test.ts`. */
function manquantes(attendues: string[]): string[] {
    return attendues.filter((nom) => !CLASSES.has(nom));
}

describe("primitives.html — the primitives gallery does show what it promises", () => {
    it('the BUTTON family: the three variants are in the markup', () => {
        expect(
            manquantes(['bouton', 'bouton--principal', 'bouton--secondaire', 'bouton--discret']),
            'button variants missing from the demonstration markup',
        ).toEqual([]);
    });

    it('the FIELD family: its four parts, and its error state', () => {
        expect(
            manquantes([
                'champ',
                'champ--erreur',
                'champ__etiquette',
                'champ__saisie',
                'champ__aide',
                'champ__erreur',
            ]),
            'field parts or state missing from the demonstration markup',
        ).toEqual([]);
    });

    it('the SURFACE family: the card, its two parts, and the separator', () => {
        expect(
            manquantes(['carte', 'carte__titre', 'carte__corps', 'separateur']),
            'surface parts missing from the demonstration markup',
        ).toEqual([]);
    });

    it('the MESSAGE family: its four tones, plus the floating variant', () => {
        expect(
            manquantes([
                'message',
                'message--succes',
                'message--alerte',
                'message--danger',
                'message--flottant',
            ]),
            'message tones or variant missing from the demonstration markup',
        ).toEqual([]);
    });
});
