//! Allocation of the numbers that distinguish our virtual output GUIDs.
//!
//! **Fix I1 of the final branch review.** The number was a simple
//! strictly monotonic counter, never recycled: `pilote::create`
//! incremented it at each creation and nothing brought it back down at
//! destruction. Yet the supervisor creates one output per window **opening**,
//! without bound — whereas the bench that preceded only created ten in its whole
//! life. At the 17th opening, the assigned GUID went out of the range the
//! inter-process purge sweeps (`purge::purger`, `1..=PLAFOND_NUMEROS`): an abrupt
//! stop then left a virtual monitor **unrecoverable without rebooting the
//! VM**, since the driver only removes through a GUID and no table survives
//! the process.
//!
//! **Recycle rather than raise the ceiling**, and it is a trade-off, not a
//! detail: raising the ceiling bounds nothing — the counter stayed growing
//! without limit, and pushing the wall to 64 or 1024 would only have delayed
//! the same defect while lengthening the purge's sweep by as much. Recycling
//! bounds the set of numbers in flight by what is really due
//! (live outputs + failed removals), a quantity the driver itself caps
//! at ten. The ceiling remains as a **hard safeguard**: beyond it, the
//! creation is refused noisily rather than assigning a number the
//! purge would never find.
//!
//! Module outside `#[cfg(windows)]` on purpose: it is pure logic, and
//! it is the piece on which the recoverability of a global system state depends.

use anyhow::Result;

/// Highest number an output can carry — hence the exact range
/// `purge::purger` must sweep to find the GUIDs of a process
/// killed outright.
///
/// Sixteen and not ten: the driver refuses the 11th simultaneous output (measured at
/// task 6), and the six numbers of margin cover failed removals, which
/// stay due without being recycled.
///
/// **It is this ceiling that is authoritative, not
/// `diagnostics::multifenetre::montee::SEARCH_CEILING`** — which says
/// how high a MEASUREMENT climbs, an unrelated question that merely
/// shared the same value.
pub const PLAFOND_NUMEROS: u16 = 16;

/// Number allocator, taking back those that were returned.
#[derive(Default)]
pub struct Numeros {
    /// Highest number ever assigned. Does not go back down: what goes back down
    /// is the content of `libres`.
    plus_haut: u16,
    /// Numbers returned by an output ACTUALLY removed, hence reassignable.
    libres: Vec<u16>,
}

impl Numeros {
    /// Assigns a number, first taking back those that were returned.
    ///
    /// Fails rather than overflowing the ceiling: an out-of-range number would be
    /// a monitor no purge could ever remove.
    pub fn attribuer(&mut self) -> Result<u16> {
        if let Some(recycle) = self.libres.pop() {
            return Ok(recycle);
        }
        anyhow::ensure!(
            self.plus_haut < PLAFOND_NUMEROS,
            "no virtual output number available any more: {PLAFOND_NUMEROS} are \
             assigned and not given back. Creating beyond would give a GUID that the \
             inter-process purge does not sweep, hence a monitor unrecoverable without \
             restarting the VM"
        );
        self.plus_haut += 1;
        Ok(self.plus_haut)
    }

    /// Returns a number whose output was **actually** removed.
    ///
    /// A number never assigned, or already returned, is ignored silently: it
    /// is not a caller error, it is the case of a GUID regenerated by
    /// the purge, or of a replayed `oublier`.
    ///
    /// NEVER call on a removal that failed: the monitor still
    /// exists, its GUID is the only handle we have on it, and reassigning this
    /// number would produce a second identical GUID.
    pub fn rendre(&mut self, numero: u16) {
        if numero == 0 || numero > self.plus_haut || self.libres.contains(&numero) {
            return;
        }
        self.libres.push(numero);
    }

    /// Numbers assigned and not yet returned. Used for the log.
    pub fn en_vol(&self) -> usize {
        self.plus_haut as usize - self.libres.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numbers_follow_each_other_as_long_as_nothing_is_given_back() {
        let mut numeros = Numeros::default();
        assert_eq!(numeros.attribuer().unwrap(), 1);
        assert_eq!(numeros.attribuer().unwrap(), 2);
        assert_eq!(numeros.attribuer().unwrap(), 3);
        assert_eq!(numeros.en_vol(), 3);
    }

    /// Defect I1 itself: a supervisor opens and closes windows without
    /// bound. With a monotonic counter, the 17th opening assigned a number
    /// outside the range swept by the purge.
    #[test]
    fn a_hundred_opens_and_closes_do_not_leave_the_ceiling() {
        let mut numeros = Numeros::default();
        for _ in 0..100 {
            let numero = numeros
                .attribuer()
                .expect("recycling must give the slot back");
            assert!(
                numero <= PLAFOND_NUMEROS,
                "number {numero} out of the purge's reach"
            );
            numeros.rendre(numero);
        }
        assert_eq!(numeros.en_vol(), 0);
    }

    /// Eight windows open at the same time — the work stream's target — then
    /// renewed indefinitely: the numbers stay in range.
    #[test]
    fn eight_simultaneous_renewed_outputs_stay_in_range() {
        let mut numeros = Numeros::default();
        let mut vivantes: Vec<u16> = (0..8).map(|_| numeros.attribuer().unwrap()).collect();
        for _ in 0..50 {
            let rendue = vivantes.remove(0);
            numeros.rendre(rendue);
            let neuve = numeros.attribuer().unwrap();
            assert!(
                neuve <= PLAFOND_NUMEROS,
                "number {neuve} out of the purge's reach"
            );
            vivantes.push(neuve);
        }
        assert_eq!(numeros.en_vol(), 8);
    }

    /// The hard safeguard: a state where nothing is returned (removals all failed)
    /// must make the creation be refused, not assign a number invisible to the
    /// purge.
    #[test]
    fn beyond_the_ceiling_creation_is_refused() {
        let mut numeros = Numeros::default();
        for _ in 0..PLAFOND_NUMEROS {
            numeros.attribuer().unwrap();
        }
        assert!(
            numeros.attribuer().is_err(),
            "the ceiling should have refused"
        );
        // A single successful removal reopens exactly one slot.
        numeros.rendre(4);
        assert_eq!(numeros.attribuer().unwrap(), 4);
        assert!(numeros.attribuer().is_err());
    }

    #[test]
    fn giving_back_an_unknown_or_already_given_back_number_creates_no_duplicate() {
        let mut numeros = Numeros::default();
        let a = numeros.attribuer().unwrap();
        numeros.rendre(a);
        // The same one twice, plus one never assigned, plus zero.
        numeros.rendre(a);
        numeros.rendre(999);
        numeros.rendre(0);
        assert_eq!(numeros.attribuer().unwrap(), a);
        assert_eq!(
            numeros.attribuer().unwrap(),
            a + 1,
            "no duplicate was put in reserve"
        );
    }
}
