-- The icons of applications: their hash, and the PROVENANCE of their
-- image. Sub-block G2.
--
-- 🔴 WHY THESE TWO COLUMNS ARE NULLABLE, WHERE THOSE OF 0004 ARE NOT
-- NULL. It is NOT a loosening: it is the measurement of 0004 applied to a
-- state that changed. On SQLite 3.50.4, an ALTER TABLE ADD COLUMN NOT NULL
-- without a DEFAULT is REFUSED as soon as the table carries a single row --
--     Cannot add a NOT NULL column with default value NULL
-- Yet `application` IS NO LONGER EMPTY since the acceptance of G1: it carries 154
-- rows on the development VM. The two columns of G2 are therefore
-- NULLABLE, AND THERE IS NO ALTERNATIVE.
--
-- ⚠️ ON A FRESH DATABASE, THE TABLE IS EMPTY AND A NOT NULL WOULD PASS. That is
-- exactly the trap of divergence E8 of G1: the test that guards this
-- property must INSERT an application BEFORE applying this migration,
-- otherwise its red cannot be reached.
--
-- 🔴 AND THAT IS WHY `NonMesuree` IS REPRESENTED BY NULL, NEVER BY 0 NOR
-- BY 256. The column is INTEGER: it CANNOT carry the word
-- `non-mesuree`, so it carries NULL. The reconstruction is unambiguous
-- because the invariant is WRITTEN, and it has THREE cases -- the fourth is
-- FORBIDDEN:
--
--   icone   source_max_px   meaning                                on the wire
--   NULL    NULL            no icon: the extraction failed         icone:null,
--                                                                  "non-mesuree"
--   non-null NULL           the icon exists, its provenance is     icone:"<hex>",
--                           not readable                           "non-mesuree"
--   non-null n              the icon exists, and its source had    icone:"<hex>",
--                           an entry of n px                       {"pixels":n}
--   NULL    n               🔴 FORBIDDEN -- no path writes it, and a test
--                           NAMES it so that it is not born from inattention
--
-- 🔴 WHAT THE `source_max_px` COLUMN IS NOT: the RENDERED size. Measured on
-- 20 August 2026 on two fabricated witnesses (agent/testdata/g2-temoin-*.ico):
-- an .ico containing ONLY ONE 48x48 entry, queried at 256, renders 256x256
-- 32bpp -- through IShellItemImageFactory as through PrivateExtractIconsW, without
-- SIIGBF_SCALEUP and EVEN with SIIGBF_BIGGERSIZEOK. The four render lines
-- of the two witnesses are identical; only the ICONDIR line differs. A
-- column carrying the rendered size would therefore be 256 everywhere, and would
-- say nothing.
--
-- The hash is that of the PNG BYTES, never of the pixels: the platform
-- RECOMPUTES the hash of what it receives, and addressing by pixels
-- would force it to DECODE the PNG to check -- that is, to ship a
-- PNG decoder in TypeScript, a new production dependency that this
-- sub-block refuses.
--
-- 🔴 THE BYTES THEMSELVES ARE NOT HERE, AND IT IS A DECISION. They live
-- on DISK, one file per hash. Three reasons, in order of their
-- weight:
--   1. A BLOB DOES NOT CROSS THE DOUBLE PASS WITHOUT LYING. PostgreSQL has no
--      BLOB type (it has bytea); SQLite, for its part, accepts ANY type
--      name by affinity -- the lint of sous-ensemble.test.ts documents it for
--      SERIAL, with a measurement to back it. Writing BYTEA would therefore pass BOTH passes
--      while meaning two different things: it is the SERIAL trap in
--      reverse, and neither of the two guards of the repository catches it.
--   2. The doctrine is already written by the spec itself, which settles upload
--      resumption in favour of a DIRECTORY LISTING, never
--      of a bookkeeping table that could diverge from the disk.
--   3. The volume: 4 576 398 bytes measured for this catalogue alone, in a
--      SQLite file that also carries sessions and tokens.
--
-- No index is added: an application is NEVER looked up BY its
-- icon. No foreign key either -- SQLite cannot add one through
-- ALTER TABLE (P1 legacy item no. 2). And ADD COLUMN rather than DROP/CREATE, for the
-- reason 0004 writes: between two gestures that assume the same thing, we
-- take the one that SHOUTS when the assumption is wrong.

-- The SHA-256 hash of the PNG, in lowercase hexadecimal. NULL = the extraction
-- failed, and it is NOT an error: an application without an icon is better
-- than an absent application.
ALTER TABLE application ADD COLUMN icone TEXT NULL;

-- The largest entry actually PRESENT in the icon directory of the
-- source. NULL = `SourceMax::NonMesuree` -- see the three-case invariant
-- above.
--
-- ⚠️ IT DOES NOT CARRY THE `_a` CONVENTION and does not need it: it is not
-- a timestamp, and the timestamp lint of sous-ensemble.test.ts therefore does not
-- look at it. INTEGER is enough -- an icon size fits very comfortably
-- in the 4 bytes of Postgres, unlike a Date.now().
ALTER TABLE application ADD COLUMN source_max_px INTEGER NULL;
