#!/usr/bin/env python3
"""Activate hook of the desk package: arm what `install` only laid down.

Protocol (see `installer/packages/runner.py` in the sibling repository, and the
docstrings of `resolve.py`/`install.py` in this package): reads
{"hw":…, "answers":…} on stdin, writes one JSON object per line on stdout.
Like `install`, this hook has NO `refuse` channel — an error here
becomes a non-zero exit code (`HookError` on the engine side), because
`activate` runs AFTER `resolve` has already validated the machine and
`install` has already written to the target disk: a failure at this stage is an
anomaly, not a decision to justify to the operator.

🔴 THE `facts` OF `resolve` ARRIVE MERGED INTO `hw`, NEVER IN A
SEPARATE `facts` KEY. Checked in `installer/packages/runner.py::run_activate`
(lines 327-337): `_run_hook(manifest, "activate",
merge_into_hw(hw, facts or {}), answers, emit=emit)` — without a `root`
parameter either (`_run_hook`'s `root` defaults to `""`, so NO `--root` is
passed in production; `argparse` below still gives it a default of
`/`, like `console/hooks/activate.py`, to stay callable the same
way by the tests). The precedence rule is in
`installer/packages/facts.py::merge_into_hw`: `hw` (the fresh detection)
wins over a fact with the same key, a fact only fills what `hw` did not
produce. No `hw` key that `resolve.py` measured (`node_version`,
`turn_ecoute`, `turn_relais`, `port`) has a known generic detector to
date, so in practice these four keys always survive the merge — but
this hook READS them from `hw`, never from a sibling `facts`, to stay correct
on the day a generic detector would produce them too.

🔴 FIX FROM THE FINAL BRANCH REVIEW (30 August 2026): this list
also carried `vm_repond`, a key that `resolve.py` NEVER measured —
it was hardcoded to `True` in the emission dict, in the very phase that this
batch established can know nothing about the VM (`resolve` runs before
`partition()`; see the head comment of `resolve.py::resoudre`). The
key was removed from the `facts`: no consumer read it, neither in this
repository (`grep -rn vm_repond hooks/`, before removal, only returned
`resolve.py` and the test fixtures) nor in the sibling repository `installer/`.
`tests/test_desk_contrat_hw.py` (guard ⑤) now refuses any future fact
that would do the same thing: a value hardcoded in the emission
dict of `resolve.py`, rather than derived from a measurement.

🔴 ARMING IS A LINK, NEVER `systemctl enable`. Same doctrine as
`console/hooks/activate.py` (the only precedent in that sibling repository):
`systemctl` fails SILENTLY in a constrained environment — a
query subcommand prints nothing —, so an `enable` that "returns"
says nothing. A link exists or raises. `hooks/assets/
desk-plateforme.service` has carried this comment since task 4.

⚠️ DELIBERATE DIFFERENCE WITH THE `console` PRECEDENT: the link created here is
RELATIVE (`../desk-plateforme.service`), not absolute
(`/etc/systemd/system/…`). An absolute link only resolves when the
`--root` in use IS `/` — which `console/hooks/activate.py` assumes
explicitly ("The link target is an ABSOLUTE path in the running system's
namespace, not in the throwaway root"). A relative link, on the other hand, resolves
correctly on both sides: under a test `--root` as under the
real `/`, `os.path.realpath()` lands on the same file — that is what
makes `os.path.exists(os.path.realpath(lien))` checkable IN TESTS, without
ever touching the real systemd of the machine running these tests.

🔴 YOU ARM NOTHING ON THIS MACHINE. `daemon-reload` and `start` only
run IF `--root` is `/` — never under a test `--root`:
reloading/starting there would drive the systemd of the INSTALLER (or of the test
bench), not that of the target. The links created guarantee anyway
that the next real boot is correct, with or without this immediate
step — same reasoning as `console/hooks/activate.py::start_now`.

The password of the initial account ONLY TRAVELS THROUGH STDIN, never through
`argv`: see `plateforme/src/admin/creer-utilisateur.ts`, which explicitly  # policy: allow-fr - real file name
REFUSES a `--password`/`--mdp`/… on the command line (`ps`
would expose a secret passed in argv to every user of the machine,
for the whole duration of the call, then in the shell history).

🔴 `--vm` OF `admin:agent` MEANS TWO THINGS DEPENDING ON THE MODE, READ IN
`plateforme/src/admin/enroler-agent.ts`:
  - in ENROLMENT mode (the one this hook uses), `--vm <name>` is the display
    NAME of the VM (`enroler-agent.ts:96`: "--vm <name> is
    required"; `enrolerLaVm` writes it as is into the `vm.nom` column,
    the `vm_id` identifier being a `randomUUID()` generated BY the command,
    never received);
  - in `--roter` mode (outside the scope of this hook), `--vm <id>` is this
    time the already assigned `vm_id` identifier (see its own refusal
    message, `enroler-agent.ts:183-184`: "it is `vm_id`, the one `--vm
    <name> --adresse <host>` printed at enrolment").
  This hook enrols only once, never rotates a secret:
  it therefore only uses the enrolment mode, with a NAME.
`--adresse` has NO default on the command side (`enroler-agent.ts:112-114`):
this hook must always provide one.

`AGENT_VM` — the variable that `scripts/run-agent.sh` sets on the Rust agent
(see `agent/src/plateforme/identite.rs`) — is the `vm_id` (the UUID) that the
platform checks against `agent_enrole` (`plateforme/src/agents/
enrolement.ts::verifyEnrolment` queries by `vm_id`), NOT the display
name passed to `--vm`: it is indeed the `vm_id=…` line of the output of
`admin:agent` that this hook copies into `AGENT_VM`, never the name given as
input.

⚠️ NEITHER THE NAME NOR THE ADDRESS OF THE WINDOWS VM ARE WIZARD ANSWERS
(`wizard.yaml` asks no question about them, on purpose — "Four questions,
and not one more"), and no known `hw` detector produces them
either (see above). `ADRESSE_VM_DEFAUT` therefore takes the value that
`console/guest/winrm_exec.py:37` already uses as the default of `GUEST_IP`
(`192.168.3.2`) — an address REALLY PINNED, not guessed:
`console/guest/domain.py` sets a static DHCP lease on this address
for the MAC address of the Windows VM that `console` provisions (desk requires
`console` as a prerequisite, see `nivuus-package.yaml`). The display name
`NOM_VM_DEFAUT`, on the other hand, IS NOT A MEASURED VALUE: it is an arbitrary
choice (a single VM exists in this deployment), documented as such
and left overridable — see the § Caveats of this task's report.
"""
import argparse
import json
import os
import pathlib
import subprocess
import sys

from administration import assign_vm_to_user, create_admin_account, enroler_agent_plateforme
from agent_payload import chemin_agent_console, construire_agent_reel, deposer_agent_console  # noqa: F401
from env_file import ACTIVATE_KEYS, add_env_variables, read_env_file
from vm import poser_projfs, poser_vb_audio

# --- What task 4 set up, and what this hook arms or completes -----------
UNITE = "desk-plateforme.service"
UNIT_DIR = "etc/systemd/system"
# ⚠️ MUST STAY IN SYNC with the `[Install] WantedBy=` of
# `hooks/assets/desk-plateforme.service`: it is that file that decides under
# which `.target.wants/` the link must live for systemd to take it into
# account at `multi-user.target` startup. `tests/test_desk_activate.py`
# checks this synchronisation by reading the unit itself.
WANTS_SUBDIR = "multi-user.target.wants"

ENV_RELATIF = "etc/nivuus/desk.env"
PLATEFORME_RELATIF = "opt/nivuus/desk/plateforme"

# See the top docstring for the justification of these two defaults.
ADRESSE_VM_DEFAUT = "192.168.3.2"
NOM_VM_DEFAUT = "windows"


def emettre(evenement: dict) -> None:
    print(json.dumps(evenement), flush=True)


# --- Arming: a link, never an `enable` -------------------------------

def armer_unite(root: pathlib.Path, unite: str) -> pathlib.Path:
    """Links `unite` into `<UNIT_DIR>/<WANTS_SUBDIR>/`. Idempotent.

    Raises `FileNotFoundError` if the unit does not exist yet under
    `<root>/<UNIT_DIR>/`: a dead link would be worse than no link, it would
    read as armed while it is not. It is the arm the task
    deliberately tests (see the Step 5 § of the plan).

    The link created is RELATIVE (`../<unite>`) — see the top docstring
    for why this choice differs from the `console` precedent.
    """
    chemin_unite = root / UNIT_DIR / unite
    if not chemin_unite.is_file():
        raise FileNotFoundError(str(chemin_unite))

    wants_dir = root / UNIT_DIR / WANTS_SUBDIR
    wants_dir.mkdir(parents=True, exist_ok=True)
    lien = wants_dir / unite

    cible = os.path.relpath(chemin_unite, wants_dir)
    if lien.is_symlink() and os.readlink(lien) == cible:
        return lien
    if lien.exists() or lien.is_symlink():
        lien.unlink()  # a REGULAR file here would be the bug, not a state
    lien.symlink_to(cible)
    return lien


def start_now(unite: str) -> list:
    """`daemon-reload` then `start <unite>`. Never raises.

    `systemctl` is legitimately unusable in a constrained
    environment (see the top docstring), and the link created by
    `armer_unite` guarantees anyway that the next real boot
    is correct — so each failure is only REPORTED, never fatal.
    Only called by `main()` when `--root` is `/`: see its
    guard, right before the call.
    """
    echecs = []
    commandes = [["systemctl", "daemon-reload"], ["systemctl", "start", unite]]
    for commande in commandes:
        try:
            proc = subprocess.run(commande, capture_output=True, text=True)
        except OSError as exc:  # systemctl absent from this PATH
            echecs.append(f"{' '.join(commande)} : {exc}")
            continue
        if proc.returncode != 0:
            detail = (proc.stderr or proc.stdout or "").strip()[:200]
            echecs.append(f"{' '.join(commande)} : {detail or proc.returncode}")
    return echecs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--phase")
    parser.add_argument("--root", default="/")
    args = parser.parse_args()
    root = pathlib.Path(args.root.rstrip("/") or "/")

    # Generic guard on the shape of the input: an unreadable JSON, or a
    # root that is not an object, must never raise a Python traceback
    # — task 3's fix (a `main()` that raised on a malformed
    # input) applies just as well here.
    try:
        contexte = json.load(sys.stdin)
    except json.JSONDecodeError as exc:
        print(f"desk activate: unreadable input, stdin is not valid JSON ({exc})",
              file=sys.stderr)
        return 1
    if not isinstance(contexte, dict):
        print("desk activate: malformed input, the JSON root must be an object",
              file=sys.stderr)
        return 1
    hw = contexte.get("hw")
    hw = hw if isinstance(hw, dict) else {}
    answers = contexte.get("answers")
    answers = answers if isinstance(answers, dict) else {}

    # `hw` carries resolve's facts, MERGED (see the top
    # docstring): `port` is among them if no generic detector has
    # already produced it under that name. Purely informative here — the port itself
    # is already baked into desk.env by `install.py` — but it is the proof
    # that this hook does read `hw`, never a `facts` key that does not exist at
    # this level of the protocol.
    port_attendu = hw.get("port")
    msg_armement = "Arming the service"
    if port_attendu:
        msg_armement += f" (expected port: {port_attendu})"

    emettre({"event": "progress", "pct": 10, "msg": msg_armement})
    try:
        armer_unite(root, UNITE)
    except FileNotFoundError as exc:
        print(f"desk activate: unit absent, nothing armed: {exc}", file=sys.stderr)
        return 1

    # Only on the REAL machine: see the top docstring.
    if str(root) == "/":
        echecs = start_now(UNITE)
        if echecs:
            print("desk activate: unit linked but not started; arming "
                  "will take effect at the next reboot", file=sys.stderr)
            for item in echecs:
                print(f"  - {item}", file=sys.stderr)

    # 🔴 TASK 6 — WHAT `desk` SETS UP IN THE VM, THROUGH THE WINRM PATH OF
    # `console`. Placed HERE, BEFORE the rest (account, enrolment), and never
    # behind the idempotence guard below (`AGENT_VM`/`AGENT_SECRET`):
    # these two setups are independent of the state of `plateforme/`
    # (`Enable-WindowsOptionalFeature` is natively idempotent — replaying
    # it breaks nothing), and gating them behind the account's idempotence
    # would make a first failure HERE, occurring AFTER an already
    # successful enrolment, never be retried by a later replay.
    #
    # 🔴 THE WINDOWS VM GATE LIVES HERE, SINCE THE FINAL BRANCH REVIEW
    # (August 30th, 2026), AND NO LONGER IN `resolve`. `hooks/resolve.py` carried
    # `if not hw.get("vm_windows"): refuser(...)`: a key that NO
    # producer of the engine sets (`common/hardware.py::detect_all()` returns
    # eight, none of that name), tested at a phase — before `partition()` — where
    # the target disk, hence the system, hence the VM, do not exist yet.
    # See the matching comment block in `resolve.py` for the
    # three complete reasons.
    #
    # HERE, the VM can exist: `activate` runs after the reboot, on the
    # installed system, with the network, and `console` — a HARD prerequisite of the
    # manifest, hence activated BEFORE `desk` — has provisioned it. The gate is
    # therefore a MEASUREMENT, never a key read: the first WinRM exchange
    # below IS the test. If it fails, it is not "ProjFS could not
    # be enabled", it is "the VM is not there", and the message says so.
    #
    # ⚠️ WHY NOT A SEPARATE, READ-ONLY PROBE BEFORE THIS ONE:
    # it would cost a second WinRM round trip that could say nothing
    # more than the first — and its success criterion (a non-empty output)
    # is not reliable, `winrm_exec.py` legitimately returning an empty output
    # for a command that prints nothing. A check that cannot
    # distinguish its two values is not a check: we keep the one that
    # can.
    emettre({"event": "progress", "pct": 25,
              "msg": "Checking the Windows VM, then setting up ProjFS "
                     "(console's WinRM path)"})
    try:
        etat_projfs = poser_projfs()
    except (FileNotFoundError, RuntimeError) as exc:
        print("desk activate: the Windows VM does not answer on console's "
              "WinRM path — desk orchestrates a Windows remote desktop over WebRTC "
              "and has nothing to do without it (console provisions it, see the "
              "'console' prerequisite of the manifest; it is HERE, after the "
              "reboot, that this condition is tested, never in "
              f"resolve, where the VM cannot exist yet): {exc}",
              file=sys.stderr)
        return 1
    # The reboot is NOTED and SAID HERE, it is never taken: see
    # hooks/vm.py::poser_projfs. An operator reading this message knows a
    # reboot of the VM remains their responsibility.
    if etat_projfs.redemarrage_requis:
        print("desk activate: ProjFS enabled in the VM; a reboot of "
              "the VM is required for it to take effect (not triggered "
              "automatically)", file=sys.stderr)

    try:
        poser_vb_audio(armee=bool(answers.get("vb_audio", False)))
    except (FileNotFoundError, RuntimeError, NotImplementedError) as exc:
        print(f"desk activate: VB-Audio setup in the VM refused: {exc}",
              file=sys.stderr)
        return 1

    # Task 7 — dropping agent.exe (see chemin_agent_console() above);
    # independent of plateforme/, never behind the idempotence guard.
    emettre({"event": "progress", "pct": 30,
              "msg": "Dropping agent.exe for console (cross build)"})
    try:
        deposer_agent_console()
    except (FileNotFoundError, RuntimeError, OSError) as exc:
        print(f"desk activate: dropping agent.exe for console refused: {exc}",
              file=sys.stderr)
        return 1

    plateforme_dir = root / PLATEFORME_RELATIF
    if not plateforme_dir.is_dir():
        print(f"desk activate: {plateforme_dir} is absent; the install hook "
              "does not seem to have run on this root", file=sys.stderr)
        return 1

    env_chemin = root / ENV_RELATIF

    # 🔴 FIX, ROUND 1 — `desk.env` MUST ALREADY EXIST AT THIS STAGE, AND
    # ITS ABSENCE IS A REFUSAL, NEVER A SILENT CREATION. Two
    # reasons, the second being the one that settles it:
    #   1. it is the SYMPTOM of a partial installation (`plateforme/`
    #      set up, `desk.env` never written or deleted since) — a problem
    #      more serious than a mere missing file, which deserves a named refusal
    #      rather than a silent fallback;
    #   2. `add_env_variables()` (below) writes through `write_text()` THEN
    #      `chmod`, exactly the pattern `install.py::write_env`
    #      abandoned (commit `92cacfb`, "a secret never readable between
    #      creation and chmod") for an atomic `os.open(..., 0o600)` — a
    #      NEW file would be born here with the process umask, briefly readable
    #      by anyone before the `chmod` catches up, and this file is about to
    #      receive `AGENT_SECRET`. Refusing here guarantees that
    #      `add_env_variables()` only EVER writes to a file already at
    #      600: `write_text()` on an EXISTING file does not touch its
    #      mode, so no window opens. `tests/test_desk_activate.py`
    #      tests this refusal (dedicated scenario: `plateforme/` set up, `desk.env`
    #      absent).
    if not env_chemin.is_file():
        print(f"desk activate: {env_chemin} is absent; the install hook does not "
              "seem to have laid down an environment file on this "
              "root (partial installation, or file deleted since) — "
              "nothing is created in its place", file=sys.stderr)
        return 1

    env_deja_pose = read_env_file(env_chemin)

    # 🔴 IDEMPOTENCE: an ALREADY SUCCESSFUL activation replays neither the creation
    # of the account, nor the enrolment. `vm.nom` has NO uniqueness constraint
    # (`plateforme/…/0001-schema.sql`: only `utilisateur.email` is  # policy: allow-fr - SQL table name
    # `UNIQUE`) — a second `admin:agent` on a replay would therefore create one more
    # ORPHAN VM at each call, never a refusal; and a
    # second `admin:utilisateur` with the SAME email would fail on the  # policy: allow-fr - npm script name
    # `UNIQUE` constraint of `utilisateur.email`. Without this guard, a replay  # policy: allow-fr - SQL table name
    # (retried by the engine, or relaunched by hand by an operator after a
    # first success) would therefore be either CORRUPTING (orphan VMs piling
    # up), or doomed to fail forever. Same doctrine
    # as `console/hooks/activate.py::run_steps` (`step.already_done()`):
    # an already completed step is NOTED, it is not replayed.
    #
    # ⚠️ WHAT THIS GUARD DOES NOT COVER: a failure BETWEEN the creation of the
    # account and the enrolment (account created, `AGENT_VM`/`AGENT_SECRET` never
    # written) makes a replay stumble on the already taken email — a
    # PARTIAL recovery outside the scope of this task, see the
    # report, § Reservations.
    if all(env_deja_pose.get(cle) for cle in ACTIVATE_KEYS):
        emettre({"event": "progress", "pct": 100,
                 "msg": "desk: already activated (AGENT_VM/AGENT_SECRET already "
                        "present in desk.env); account and enrolment skipped"})
        emettre({"event": "done"})
        return 0

    email = str(answers.get("admin_email") or "")
    mot_de_passe = str(answers.get("admin_password") or "")
    if not email or not mot_de_passe:
        print("desk activate: answers.admin_email and answers.admin_password "
              "are required and absent", file=sys.stderr)
        return 1

    # `admin:utilisateur`/`admin:agent` read their configuration (which  # policy: allow-fr - npm script name
    # database, which SQLite file…) from `process.env` — see
    # `plateforme/src/config.ts::lireConfig`. These are NOT the variables
    # of this Python process: they live in desk.env, written by
    # `install.py`, and must therefore be merged into the environment
    # passed to `npm`, otherwise the administration commands
    # would open a database different from the one the started service will
    # really serve.
    env_npm = dict(os.environ)
    env_npm.update(env_deja_pose)

    emettre({"event": "progress", "pct": 40, "msg": "Creating the administrator account"})
    _identifiant, raison = create_admin_account(plateforme_dir, email, mot_de_passe, env_npm)
    if raison:
        print(f"desk activate: account creation refused: {raison}", file=sys.stderr)
        return 1

    emettre({"event": "progress", "pct": 70, "msg": "Enrolling the agent"})
    nom_vm = os.environ.get("DESK_VM_NOM", NOM_VM_DEFAUT)
    adresse_vm = os.environ.get("GUEST_IP", ADRESSE_VM_DEFAUT)
    result, raison = enroler_agent_plateforme(plateforme_dir, nom_vm, adresse_vm, env_npm)
    if raison:
        print(f"desk activate: agent enrolment refused: {raison}", file=sys.stderr)
        return 1
    vm_id, secret = result

    add_env_variables(env_chemin, dict(zip(ACTIVATE_KEYS, (vm_id, secret))))

    # 🔴 TASK 13 — A HOLE FOUND IN PRODUCTION ON AUGUST 29TH, 2026: `enroler_agent_
    # plateforme()` (hence `admin:agent`, hence `enrolerLaVm`) does
    # `INSERT INTO vm(id, nom, adresse)` WITHOUT ever passing a user —
    # `vm.utilisateur_id` stayed NULL, and  # policy: allow-fr - SQL column
    # `plateforme/src/http/routes-applications.ts` had announced it IN SO MANY WORDS since before this
    # fix: "as long as no VM is assigned, EVERY AUTHENTICATED USER
    # SEES ALL THE VMS: it is NOT an isolation" — and the
    # symptom MEASURED at the owner's was the mirror of that same cell
    # left NULL: `GET /vm` returned `{"vms":[]}` for an account that was
    # indeed created, hence an empty hub. Repaired on the running instance by hand
    # (`npm run admin:attribuer -- --email … --vm windows`); what follows is
    # what was missing so that a FRESH installation never again needs
    # that manual repair.
    #
    # 🔴 PLACEMENT: NEITHER IN THE IDEMPOTENCE SHORT-CIRCUIT ABOVE, NOR OUTSIDE
    # ANY GUARD — the two obvious traps, and neither of them works:
    #   - IN the short-circuit (which only runs ON REACTIVATION, once
    #     `AGENT_VM`/`AGENT_SECRET` are already written): the NORMAL pass —
    #     the one that runs ONLY ONCE per package, at activation — would
    #     NEVER reach it. It is exactly the hole found in
    #     production: an installation that never replays activation never
    #     catches up on its own.
    #   - OUTSIDE any guard (replayed at EACH call, short-circuit included):
    #     `admin:attribuer` IS NOT idempotent for a replay — the orchestrator
    #     refuses `vm-deja-attribuee` as soon as `utilisateur_id` is no longer NULL,  # policy: allow-fr - SQL column
    #     EVEN for reassignment to the same user
    #     (`inventaire-statique.ts::attribuer`, read ①). Replaying at each
    #     reactivation would therefore make EVERY reactivation fail after the
    #     first success, on a refusal that says nothing false but
    #     is not a failure either.
    #   It therefore lives HERE, as the CONTINUATION of the normal path — protected
    #   by THE SAME guard as the account and the enrolment just above (the
    #   short-circuit skips it just as much as them): it runs only
    #   once, in the pass that has just created that account and enrolled
    #   that agent — never in the following reactivations.
    #
    # ⚠️ WHAT THIS PLACEMENT DOES NOT COVER, SAME LIMIT AS THE IDEMPOTENCE
    # GUARD ABOVE (see its own comment): a failure HERE
    # occurs AFTER `AGENT_VM`/`AGENT_SECRET` are already written (previous
    # line) — a reactivation will therefore short-circuit from now on BEFORE
    # reaching this assignment, without ever retrying it. It is the
    # LEAST bad choice of the two possible orders: writing these two variables
    # AFTER the assignment would instead reopen, on this same failure, the REPLAY of
    # `admin:agent` — which, for its part, creates one more ORPHAN VM at each
    # call (see the idempotence guard's comment above): a
    # worse regression than the one being fixed here. An assignment missed at
    # this point stays diagnosable (the message below names the cause)
    # and repairable BY HAND through this same `npm run admin:attribuer` — it is
    # exactly how the real instance of August 29th, 2026 was repaired.
    emettre({"event": "progress", "pct": 90,
             "msg": "Assigning the VM to the administrator account"})
    _sortie_attribution, raison = assign_vm_to_user(plateforme_dir, email, vm_id, env_npm)
    if raison:
        print(f"desk activate: VM assignment refused: {raison}", file=sys.stderr)
        return 1

    emettre({"event": "progress", "pct": 100,
             "msg": "desk: service armed, account created, agent enrolled, VM assigned"})
    emettre({"event": "done"})
    return 0


if __name__ == "__main__":
    sys.exit(main())
