//! Neutralisation of Windows' pointer acceleration and sensitivity.
//!
//! `SendInput` in relative mode goes through the session's acceleration curve and
//! speed setting — without neutralisation, aiming is
//! distorted and non-linear, which is unacceptable in games. It is the
//! "major trap" of the scoping.
//!
//! The setting is applied WITHOUT `SPIF_UPDATEINIFILE`: it holds for the
//! current session and disappears at disconnection. The agent therefore leaves
//! no persistent trace on the VM, and the setting cannot be forgotten
//! during a reprovisioning — it is reapplied at each start-up.
//!
//! No side effect on the absolute mouse, which already ignores these settings.

#[cfg(windows)]
mod win {
    use anyhow::{Context, Result};
    use windows::Win32::UI::WindowsAndMessaging::{
        SystemParametersInfoW, SPI_GETMOUSE, SPI_GETMOUSESPEED, SPI_SETMOUSE, SPI_SETMOUSESPEED,
        SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS,
    };

    /// 1:1 speed notch. The scale goes from 1 to 20; 10 is the only notch that
    /// neither multiplies nor divides the movement.
    const VITESSE_1_POUR_1: usize = 10;

    /// Acceleration thresholds. The first two are the steps, the
    /// third enables acceleration or not: all at zero disables it.
    const SANS_ACCELERATION: [u32; 3] = [0, 0, 0];

    pub fn neutraliser() -> Result<String> {
        // Checked against the definition generated by windows-rs 0.62 (the brief
        // was only a plausible form): `SystemParametersInfoW` does have the
        // signature `(uiaction, uiparam: u32, pvparam: Option<*mut c_void>,
        // fwinini) -> windows_core::Result<()>` for BOTH actions,
        // including SPI_SETMOUSESPEED — the third parameter changes MEANING
        // (pointer to a datum, or the datum itself disguised as a
        // pointer) depending on the action, but not TYPE. No signature
        // correction was therefore necessary here, unlike
        // `ClientToScreen` in `input.rs`.
        let mut params = SANS_ACCELERATION;
        unsafe {
            SystemParametersInfoW(
                SPI_SETMOUSE,
                0,
                Some(params.as_mut_ptr().cast()),
                SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS(0),
            )
        }
        .context("SPI_SETMOUSE")?;

        // SPI_SETMOUSESPEED is the announced asymmetry: unlike
        // SPI_SETMOUSE, the value is not pointed to by `pvparam`, it IS
        // `pvparam`, cast to a pointer (that is how Win32 documents
        // this precise action — an integer carried by a pointer
        // parameter, not an error of the brief).
        unsafe {
            SystemParametersInfoW(
                SPI_SETMOUSESPEED,
                0,
                Some(VITESSE_1_POUR_1 as *mut core::ffi::c_void),
                SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS(0),
            )
        }
        .context("SPI_SETMOUSESPEED")?;

        // Reading back: a call that succeeds does not guarantee that the value
        // was taken, notably under group policy.
        let mut relu = [0u32; 3];
        unsafe {
            SystemParametersInfoW(
                SPI_GETMOUSE,
                0,
                Some(relu.as_mut_ptr().cast()),
                SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS(0),
            )
        }
        .context("SPI_GETMOUSE")?;

        let mut vitesse: u32 = 0;
        unsafe {
            SystemParametersInfoW(
                SPI_GETMOUSESPEED,
                0,
                Some((&mut vitesse as *mut u32).cast()),
                SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS(0),
            )
        }
        .context("SPI_GETMOUSESPEED")?;

        Ok(format!(
            "seuils relus = {relu:?}, vitesse relue = {vitesse} (attendu : [0, 0, 0] et {VITESSE_1_POUR_1})"
        ))
    }
}

#[cfg(windows)]
pub use win::neutraliser;
