// The RULE of the per-application PWA manifest. PURE: no DOM, no `fetch`,
// no clock. It takes a name, an identifier and an icon's bytes,
// and returns the manifest object. That is all, and it is what makes it testable
// on the host.
//
// 🔴 WHY THIS MANIFEST IS BUILT HERE RATHER THAN SERVED BY A ROUTE.
// A `<link rel="manifest">` is fetched by the browser WITHOUT an
// `Authorization` header, exactly like the icons it names — and sub-project
// ⑤ sets NO cookie, its bearer living in `localStorage`, which does not
// travel on any request the browser emits on its own. Serving this
// manifest would therefore require opening a route that is authenticated today,
// that is, a SECURITY DECISION `routes-icone.ts:20-26` leaves
// explicitly to the repository owner. The page, for its part, is authenticated:
// it reads everything through `fetch`, and publishes what it read. **No route
// changes, no bearer check is skipped.**
//
// 🔴 TWO CONSTRAINTS MEASURED BY GATE P0, AND WHICH NOTHING ANNOUNCED.
// Logs: `docs/superpowers/plans/journaux-gestion-apps-g5/`.
//
//   ① THE URLS MUST BE ABSOLUTE. Under a manifest published as `blob:`, the
//      resolution base is the `blob:` URL itself, which is not a usable
//      base. A `start_url: '/shell.html'` — the shape of any
//      manifest served over HTTP — gets REFUSED:
//        « property 'start_url' ignored, URL is invalid. »
//        « property 'scope' ignored, URL is invalid. »
//      plus `start-url-not-valid` for installability, and
//      `beforeinstallprompt` that does not fire. Measured over 2 runs, and
//      REPLAYABLE: it is probe `f` of `instrument/porte-p0.mjs`, kept
//      for that. **It is the difference between an installable manifest and a
//      refused manifest, not a writing detail.**
//
//   ② THE ICON THRESHOLD IS 144, NOT 192. Chromium NAMES it in its
//      report: `minimum-icon-size-in-pixels: 144`. ④'s design writes
//      "below 192 px" for criterion ①'s RED run. Without consequence
//      on that RED run, whose control icon is 128 — under BOTH thresholds —,
//      but a successor setting 160 believing they were under the threshold
//      would get a GREEN and read their failed red run as a correct product.

/// What one must know about an application to build it a manifest.
export interface Sujet {
    /// The application's identifier — a UUID generated by the platform.
    id: string;
    nom: string;
    /// The bytes of the icon's PNG, or `undefined` if there is none.
    ///
    /// 🔴 ITS SIZE IS READ FROM ITS BYTES, NEVER DECLARED BY THE CALLER.
    /// A first draft took an optional `coteIcone` that was 256 by
    /// default — the only size the store knows
    /// (`agent/src/apps/icone/extraction.rs:45`, `const COTE: i32 = 256;`).
    /// **The acceptance run showed it was WRONG**: the control application, whose
    /// icon is 128, published a manifest announcing `256x256`. Chromium
    /// caught it — it DECODES the image, and returns `no-acceptable-icon` — but
    /// **a manifest that lies about what it carries is a defect even when the
    /// browser catches it**: on a 200 px icon announced as 256, it
    /// would have accepted, and the system would have scaled an image it
    /// believed larger.
    icone?: Uint8Array;
    /// The accent colour, as `#rrggbb`.
    ///
    /// ❌ "IT NEVER ARRIVES TO DATE" — WRITTEN HERE BY SLICE D OF
    /// THIS SUB-BLOCK, AND MADE FALSE BY ITS OWN SLICE F, a few commits
    /// later. **It arrives**: `Application` carries `accent` since
    /// `PLATEFORME_VERSION = 5`, the column exists (migration `0007`), and the
    /// route serves it. Measured on the VM: **149 accents over 156 applications,
    /// 87 distinct values**, Photoshop returning its blue and Illustrator its
    /// orange. The plan's divergence E1 is therefore **closed**, and no longer
    /// merely declared.
    ///
    /// ⚠️ WHAT REMAINS TRUE: it is **per APPLICATION**, not to be confused
    /// with sub-project ①'s, which is **per WINDOW**. And it stays
    /// OPTIONAL here — **7 applications of the VM have an icon WITHOUT having
    /// an accent**, because clause 5 of `dominante` (too pale, too
    /// dark, too transparent) is reachable on real data.
    /// Sub-project ①'s is **per WINDOW**, arrives during the session
    /// on the WebRTC channel, and does not describe the same thing. The member is
    /// OPTIONAL, and its absence makes `theme_color` OMITTED — never set to an
    /// invented value.
    ///
    /// Like `fond`, it comes from the live theme or the database — never from a
    /// constant of this file (see the §7.2 box below).
    accent?: string;
    /// The extensions this application opens.
    ///
    /// ⚠️ EMPTY MAKES `file_handlers` OMITTED ENTIRELY, rather than declaring
    /// a handler that accepts nothing: Chromium parses this member — measured —
    /// and an empty `accept` would be a pointless entry.
    associations?: readonly string[];
}

/// The manifest, in the shape `JSON.stringify` will publish.
export interface Manifeste {
    name: string;
    short_name: string;
    id: string;
    start_url: string;
    scope: string;
    display: string;
    display_override: string[];
    background_color: string;
    theme_color?: string;
    icons: { src: string; sizes: string; type: string; purpose: string }[];
    file_handlers?: { action: string; accept: Record<string, string[]> }[];
}

/// The extension → MIME type map. **It lives HERE, and only once.**
///
/// 🔴 THAT IS WHY ASSOCIATIONS TRAVEL AS EXTENSIONS AND NOT AS MIME
/// (decision D13 of G5's plan): a MIME type is not a property of the
/// VM, it is a convention of the Web. Making it travel would double this table —
/// in Rust **and** in TypeScript — for data the agent has no way
/// of knowing better than us.
///
/// ⚠️ THESE TYPES ARE A CHOICE, NOT A STANDARD: neither `.msi` nor `.bat` have
/// an unambiguous IANA registration, no more than most office
/// extensions. **None is calibrated.**
///
/// ⚠️ AN EXTENSION ABSENT FROM THIS TABLE FALLS BACK TO
/// `application/octet-stream`, which is **the honest type for "bytes
/// we know nothing about"** — never a silent omission of the entry.
const MIME_PAR_EXTENSION: Record<string, string> = {
    '.txt': 'text/plain',
    '.log': 'text/plain',
    '.md': 'text/markdown',
    '.csv': 'text/csv',
    '.json': 'application/json',
    '.xml': 'application/xml',
    '.pdf': 'application/pdf',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.webp': 'image/webp',
    '.svg': 'image/svg+xml',
    '.zip': 'application/zip',
    '.msi': 'application/x-msi',
    '.exe': 'application/vnd.microsoft.portable-executable',
    '.bat': 'application/x-bat',
};

/// The MIME of an extension, or the type of unknown bytes.
export function mimeDe(extension: string): string {
    return MIME_PAR_EXTENSION[extension.toLowerCase()] ?? 'application/octet-stream';
}

/// Groups extensions into the `accept` map of a `file_handler`.
///
/// 🔴 SEVERAL EXTENSIONS CAN SHARE A MIME — `.txt` and `.log` are
/// both `text/plain` —, and the manifest's map is **MIME → list**.
/// Writing one entry per extension would overwrite the previous one, and an
/// application opening both would only see one.
export function accepterDepuis(extensions: readonly string[]): Record<string, string[]> {
    const accept: Record<string, string[]> = {};
    for (const extension of extensions) {
        const mime = mimeDe(extension);
        const deja = accept[mime];
        if (deja === undefined) accept[mime] = [extension];
        else if (!deja.includes(extension)) deja.push(extension);
    }
    return accept;
}

/// 🔴 THERE IS NO COLOUR WRITTEN IN THIS FILE, AND IT IS NOT A MATTER OF TASTE:
/// ⑥'S CHECK §7.2 SWEEPS `.ts` FILES AS MUCH AS `.css` ONES. A first
/// draft set `const FOND_MANIFESTE = '#…'` here and the check flagged it —
/// along with two literals of the test. **Widening its exclusion would have satisfied the
/// check by EMPTYING it**, which this repository fights; the colours therefore
/// became PARAMETERS, which the page reads from the live theme through
/// `getComputedStyle` (the path ⑥'s spec §4.1 sanctions, and which
/// `design/galerie.ts` already uses). **There is only one source of truth
/// for a colour, and it is `tokens.css`.**

/// The PNG as `data:`, without a dependency.
///
/// ⚠️ `btoa` AND NOT `Buffer`: `client/` does not have `@types/node`, and a module
/// written with `Buffer` passes under Vitest then BREAKS `npm run typecheck` —
/// a trap measured by sub-block P2 (`TS2580 Cannot find name 'Buffer'`).
export function versDataUrl(octets: Uint8Array): string {
    let binaire = '';
    // In batches: `String.fromCharCode(...very_long)` overflows the call
    // stack, and a 256×256 icon counts in tens of thousands
    // of bytes.
    const PAQUET = 0x2000;
    for (let i = 0; i < octets.length; i += PAQUET) {
        binaire += String.fromCharCode(...octets.subarray(i, i + PAQUET));
    }
    return `data:image/png;base64,${btoa(binaire)}`;
}

/// The side of a PNG, read from its IHDR header — or `undefined` if these bytes
/// are not one.
///
/// The structure is fixed and will stay so: an 8-byte signature, then the
/// length (4) and the type (4) of the first chunk, which MUST be `IHDR`, then
/// the width (4) and the height (4), big-endian.
///
/// ⚠️ IT RETURNS THE WIDTH, and the manifest uses it for BOTH dimensions:
/// a non-square icon would be badly described there. The store only produces
/// square ones, and it is a property of the AGENT, not of this module — hence the
/// explicit check rather than a tacit assumption.
export function cotePng(octets: Uint8Array): number | undefined {
    const SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
    if (octets.length < 24) return undefined;
    for (let i = 0; i < SIGNATURE.length; i += 1) {
        if (octets[i] !== SIGNATURE[i]) return undefined;
    }
    // 'I','H','D','R' at bytes 12 to 15.
    if (octets[12] !== 0x49 || octets[13] !== 0x48 || octets[14] !== 0x44 || octets[15] !== 0x52) {
        return undefined;
    }
    const entier = (d: number): number =>
        octets[d] * 0x1000000 + octets[d + 1] * 0x10000 + octets[d + 2] * 0x100 + octets[d + 3];
    const largeur = entier(16);
    const hauteur = entier(20);
    if (largeur <= 0 || largeur !== hauteur) return undefined;
    return largeur;
}

/// Builds an application's manifest.
///
/// `origine` is `location.origin` — WITHOUT a trailing slash. `fond` is the
/// value of `--fond-0` READ FROM THE LIVE THEME, never a constant from here.
///
/// 🔴 THE PLAN'S DECISION D9 — "`start_url` POINTS AT THE SHELL PAGE, AND NOT THE
/// HUB" — IS REVERSED SINCE AUGUST 31ST, 2026, BY DECISION OF THE REPOSITORY
/// OWNER. The hub became the product's ONLY surface (plan
/// `2026-08-31-navigation-hub-unique`): it is now IT that holds the
/// control session, and `client/shell.html` is only a permanent redirect
/// to `/` (`client/src/bureau/redirection.ts`). `start_url`
/// therefore migrates to the ROOT — see the comment on `id`, just below,
/// for what DOES NOT move and why.
///
/// 🔴 `scope` IS SHARED, SO IT IS `id` THAT CARRIES THE IDENTITY. Two
/// applications cannot have two disjoint `scope`s — since
/// August 31st, 2026, `id` (`/shell.html?app=`) and `start_url` (`/?app=`) NO LONGER
/// live under the same path, but both stay under the same
/// ORIGIN, which is all a root `scope` (`${base}/`) can
/// distinguish — naming it by `/shell.html` alone would have become wrong. ⚠️ That
/// two manifests with the same `scope` and distinct `id`s produce two
/// DISTINCT applications **is not measurable by G5's setup**: it
/// would take installing two, and the host has no graphical interface.
export function batirManifeste(sujet: Sujet, origine: string, fond: string): Manifeste {
    const base = origine.replace(/\/$/, '');
    const app = encodeURIComponent(sujet.id);
    const manifeste: Manifeste = {
        name: sujet.nom,
        short_name: sujet.nom,
        // 🔴 `id` AND `start_url` DIVERGE SINCE AUGUST 31ST, 2026, AND IT IS
        // DELIBERATE.
        //
        // `id` is the IDENTITY of the installed application. Changing it is not
        // an update: it is a SECOND application, the first one
        // becoming orphaned. It therefore stays frozen on `shell.html?app=`, the
        // value carried by installations already made — and since the
        // manifest is published as `blob:` (see this file's header), an
        // installed PWA will NEVER reread its own: it will open `shell.html`
        // forever, where `client/src/bureau/redirection.ts` catches it.
        //
        // `start_url`, for its part, migrates to the ROOT: the hub is served there and
        // now holds the control session there (owner's decision,
        // August 31st, 2026). It is the value FUTURE installations
        // will take.
        //
        // ⚠️ IT STAYS WITHIN THE `scope` (`${base}/`), a condition Chromium
        // checks and refuses in so many words otherwise.
        id: `${base}/shell.html?app=${app}`,
        start_url: `${base}/?app=${app}`,
        scope: `${base}/`,
        display: 'standalone',
        // The DECLARATION of the Window Controls Overlay. What G5 brings is
        // that it is set, and it claims nothing more: WCO only exists
        // in an installed PWA window, and a headless Chromium
        // installs none. Explicit fallback to `standalone`.
        display_override: ['window-controls-overlay', 'standalone'],
        background_color: fond,
        icons: [],
    };
    if (sujet.accent !== undefined) manifeste.theme_color = sujet.accent;
    if (sujet.associations !== undefined && sujet.associations.length > 0) {
        // ⚠️ THE `action` IS WITHIN THE `scope`, AND IT IS A MEASURED REQUIREMENT:
        //    an out-of-scope `action` makes Chromium return, verbatim,
        //    « property 'action' ignored, should be within scope of the
        //    manifest. » then « FileHandler ignored. Property 'action' is
        //    invalid. » — it is indeed this probe that established that
        //    Chromium DOES parse `file_handlers`.
        manifeste.file_handlers = [
            { action: `${base}/hub.html?app=${app}`, accept: accepterDepuis(sujet.associations) },
        ];
    }
    // 🔴 AN ICON WHOSE SIZE WE CANNOT READ IS NOT DECLARED.
    //    Setting `256x256` by default would be asserting what we do not know, and
    //    it is exactly the defect the acceptance run found.
    const cote = sujet.icone === undefined ? undefined : cotePng(sujet.icone);
    if (sujet.icone !== undefined && cote !== undefined) {
        manifeste.icons.push({
            src: versDataUrl(sujet.icone),
            sizes: `${cote}x${cote}`,
            type: 'image/png',
            // `any maskable` would make the system crop the icon on the
            // platforms applying it; the store guarantees no
            // safe zone, hence `any` alone.
            purpose: 'any',
        });
    }
    return manifeste;
}
